apiVersion: core.crd.fuxiansen.com/v1
kind: Application
metadata:
  labels:
    app.kubernetes.io/name: i-operator
    app.kubernetes.io/managed-by: kustomize
  name: application-sample
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
