apiVersion: core.crd.fuxiansen.com/v1
kind: Application
metadata:
  labels:
    app.kubernetes.io/name: i-operator
    app.kubernetes.io/managed-by: kustomize
  name: application-sample
spec:
  replicas: 3
  template:
    spec:
      containers:
      - name: nginx
        image: swr.cn-north-4.myhuaweicloud.com/ddn-k8s/docker.io/nginx:1.27.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80